[ClassVersion("1.0.0"), FriendlyName("ROSSDatabase")]
class VE_ROSSDatabase : OMI_BaseResource
{
    [Key, Description("RES ONE Service Store database server name/instance name")] String DatabaseServer;
    [Key, Description("RES ONE Service Store database name")] String DatabaseName;
    [Required, Description("File path containing the RES ONE Service Store MSIs or the literal path to the legacy console/Sync Tool MSI")] String Path;
    [Required, Description("New Microsoft SQL username/password to create"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Required, Description("Existing Microsoft SQL database credentials used to create the database"), EmbeddedInstance("MSFT_Credential")] String SQLCredential;
    [Required, Description("New RES ONE Service Store Catalog Services password"), EmbeddedInstance("MSFT_Credential")] String CatalogServicesCredential;
    [Write, Description("Path to RES ONE Service Store license file")] String LicensePath;
    [Write, Description("RES ONE Service Store component version to be installed, i.e. 8.0.3.0")] String Version;
    [Write, Description("Specified path is a literal file reference")] Boolean IsLiteralPath;
    [Write, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
    [Read, Description("Windows Installer Product Name")] String ProductName;
};
